language: ruby
# Making sure Travis gets the required gems
before_install:
    - travis_retry gem install jekyll

# We test simply that Jekyll works correctly.
script: jekyll build

branches:
    only:
        - develop
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
