# Sets basic properties of the site, such as where various files can be found.
source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
include: ['.htaccess']
exclude: []
keep_filte: ['.git','.svn']
timezone: nil

future: true
show_drafts: nil
limit_posts: 0
pygments: true

relative_permalinks: true

permalink: date
paginate_path: 'page:num'

#Specifies metadata
author: Travis Scholten
description: Personal Webpage for Travis Scholten
keywords: Travis Scholten, Quantum Computation, Quantum Information

# Specifies the markdown language to be used.
markdown: redcarpet

excerpt_separator: "\n\n"

# Sets properties related to URLs
safe: false
port: 4000
url: http://localhost:4000
lsi: false

coderay:
coderay_wrap: div
coderay_line_numbers: inline
coderay_line_numbers_start: 1
coderay_tab_width: 4
coderay_bold_every: 10
coderay_css: style
